### ISSUE TITLE
Attempting to export tree containing a sound with a script named 'Play' fails.

### ISSUE THREAD

**Issue by Agapurnis** [Validark/rbxts-Object-To-Tree#3]
This occurs when using the 'TS types' export option. I believe this is occurring because this might be a reserved name for a built-in function for sounds, but I'm not sure. If that is the case, there may be other key-words for other object variants that could cause this same issue.

Sample Tree:
```
...
└── [SOUND] <anything>
    └──  [SCRIPT] Play
 ```
Attempting to generate a tree which contains something similar to that pictured above (a sound with a script that has the name 'Play', case sensitive¹) will cause the following error to be displayed:
`cloud_<ID>.rbxts-object-to-tree.Main.generateTree:219: attempt to index function with 'Name'`

¹ Although I mentioned this being case sensitive, a lowercase 'play' will also cause this issue, but not a 'plAY'.

Apologies if I missed something, this is my first git issue so I may have provided inadequate information.

**Comment by Dionysusnu** [comment]
Seems like it's using dot or index access, which will pick the method over the child. Should be switched to use FindFirstChild.

**Comment by Validark** [comment]
Fixed with https://github.com/Validark/rbxts-Object-To-Tree/releases/tag/v0.4.0
